name-map:
  ⛔ 广告拦截: adblock
  🚀 选择代理: proxy
  🌐 突破锁区: region
  DIRECT: direct

categories:
  redir:
    - "->"
    - OVERALL
  JP:
    - JP
    - Japan
    - 日
    - 🇯🇵
  US:
    - US
    - United States
    - 美
    - 🇺🇸
  CN:
    - CN
    - China
    - 中国
    - 🇨🇳
  HK:
    - HK
    - Hong Kong
    - 港
    - 🇭🇰
  TW:
    - TW
    - Taiwan
    - 台
    - 🇹🇼
  CA:
    - CA
    - Canada
    - 加拿大
    - 🇨🇦
  FR:
    - FR
    - French
    - 法
    - 🇫🇷
  SG:
    - SG
    - Singapore
    - 新加坡
    - 狮城
    - 🇸🇬